name: Manual Build

on:
  workflow_dispatch:
    inputs:
      repeats:
        description: "Number of repeats"
        required: true
        default: "5"
        type: string

      data_path:
        description: "Path to data folder"
        required: true
        default: "./data/main/"
        type: choice
        options:
          - ./data/main/
          - ./data/100x100/
          - ./data/200x200/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y g++ libopencv-dev pkg-config python3-pip
          pip3 install --no-cache-dir matplotlib

      - name: Run build script
        run: |
          chmod +x $GITHUB_WORKSPACE/build.sh
          $GITHUB_WORKSPACE/build.sh
        env:
          DATA_PATH: ${{ github.event.inputs.data_path }}
          REPEATS: ${{ github.event.inputs.repeats }}


      - name: Prepare result.png
        run: |
          cp "${{ github.event.inputs.data_path }}_result.png" ./_result.png

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-results
          path: |
            result.txt
            execution_time.png
            _result.png
